### PR TITLE
Replay system (re)implementation

### PR DESCRIPTION
**Pull request by UnderSet**
This took *way* too long for me to make. Remember #86? Yeah this is me finally getting a step in that direction done.

The replay system is now mostly usable. There's just a few things I'd like fixed, but overall it works quite well in my experience.

**HAS *NOT* BEEN TESTED WITH 2+ PLAYERS. I'll get to this eventually, I just don't have another PC to test it with** *(oof)*.

Things I (think) still need to do before merging this:
- [ ] Fix the tick counter on clientside HUD while playing replay
- [ ] Get the fullbody animations working during a replay, it currently doesn't for some reason
- [ ] Allow saving replays with a different filename (currently saves to `beatrun\replays\<map name>\replaydump.txt`)

I'd personally try and get those two done myself, but I just can't for some reason. If anyone has any feedback, let me know.

*P.S: I spent way longer working on this than I should have, I really need to take a break from coding this.*

### CODE REVIEW

**Comment by JonnyBro** [comment]
> HAS NOT BEEN TESTED WITH 2+ PLAYERS. I'll get to this eventually, I just don't have another PC to test it with (oof).

I can help with testing this in MP.

**Comment by UnderSet** [comment]
I'm closing this one for now, I think I'll need to rewrite quite a bit of this code to get all features of the system working before merging. That'll take a while though, I've got a lot of things interrupting this right now.

**Comment by UnderSet** [comment]
Quick update from me if anyone's bothered to read this PR: I'm gonna stop working on this, partly because of GitHub's forced 2FA which I can't be bothered to set up **and trust to work when I actually need it** (2FA almost locked me out of Discord once).

I'll move over to something else like GitLab for the time being. Screw forced 2FA. Maybe I'll return to this once I get enough motivation, but for now screw it.

**Comment by JonnyBro** [comment]
oh wow, i have a gitlab account

**Comment by LostTrackpad** [comment]
Quick heads-up to anyone watching this PR:
> ...GitHub's forced 2FA* which I can't be bothered to set up **and trust to work when I actually need it** (2FA almost locked me out of Discord once).
> - [My earlier comment from my old account (@UnderSet) on Jan 24, 2024](https://github.com/JonnyBro/beatrun/pull/125#issuecomment-1908160951)

This is my new account (no seriously, it even has the same email) and yep, I got locked out thanks to 2FA. So, uh, yeah this PR's never getting done. Thanks GitHub, very not-cool.

**Pull request closed without merging**
